# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ci-cd-heroku
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci-cd-heroku:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    - name: use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'

    - name: install
      run: npm ci
      
    - name: build
      run: npm run build --if-present

    - name: tests
      run: npm run test:ci --passWithNoTests
      env:
        CI: true

    - name: add heroku remote
      if: ${{success()}}
      run: |
        echo Success
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git

    - name: deploy to heroku
      run: git push heroku HEAD:main -f
    
